const data = [
    {
        "ID": 2,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ABDEEL",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 3,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ABEL",
        "Book": "GENESE",
        "Chapter": 3,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ADÃO IRMÃO DE CAIM E PASTOR DE OVELHAS"
    },
    {
        "ID": 4,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ABIDA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIDIAN E NETO DE ABRAÃO"
    },
    {
        "ID": 5,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ABIMAEL",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 28,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 6,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ABIMELECH",
        "Book": "GENESE",
        "Chapter": 20,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE GERAR"
    },
    {
        "ID": 7,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ABRÃO/ABRAÃO",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE TERA"
    },
    {
        "ID": 8,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ACAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 27,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESER NETO DE SEIR"
    },
    {
        "ID": 9,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ACBOR",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 38,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PAI DO REI BAAL-ANAN"
    },
    {
        "ID": 10,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ADA",
        "Book": "GENESE",
        "Chapter": 3,
        "Verse": 19,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER DE LAMECH"
    },
    {
        "ID": 11,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ADAD",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 35,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BEDAD E REI DE EDOM"
    },
    {
        "ID": 12,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ADÃO",
        "Book": "GENESE",
        "Chapter": 2,
        "Verse": 19,
        "Lifespan": 930,
        "Complement": "PRIMEIRO HOMEM"
    },
    {
        "ID": 13,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ADAR",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 39,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE EDOM"
    },
    {
        "ID": 14,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ADORAM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 27,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 15,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AGAR",
        "Book": "GENESE",
        "Chapter": 16,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "EGÍPCIA E SERVA DE SARAI"
    },
    {
        "ID": 16,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AGI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GAD E NET DE JACÓ"
    },
    {
        "ID": 17,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AJA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ZIBEON E NETO DE SEIR"
    },
    {
        "ID": 18,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ALIOBAMA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 41,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 19,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ALMODAD",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 20,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ALVA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 40,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 21,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ALVAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SOBAL E NETO DE SEIR"
    },
    {
        "ID": 22,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AMALEC",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 12,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ELIFAZ COM TIMNA"
    },
    {
        "ID": 23,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AMRAFEL",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE SINEAR"
    },
    {
        "ID": 24,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ANA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ZIBEON E NETO DE SEIR"
    },
    {
        "ID": 25,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ANA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 26,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ANA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MÃE DE AOLIBAMA MULHER DE ESAÚ"
    },
    {
        "ID": 27,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ANAMIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 28,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ANER",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "CONFEDERADO DE ABRÃO"
    },
    {
        "ID": 29,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AOLIBAMA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER DE ESAÚ FILHA DE ANA E ZIBEON, HEVEU."
    },
    {
        "ID": 30,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARAM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SEM E NETO DE NOÉ"
    },
    {
        "ID": 31,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARAM",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE KEMUEL E NETO DE NACOR"
    },
    {
        "ID": 32,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 28,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DISAN E NETO DE SEIR"
    },
    {
        "ID": 33,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARD",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 34,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARELI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GAD E NET DE JACÓ"
    },
    {
        "ID": 35,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARFACHAD",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SEM E NETO DE NOÉ"
    },
    {
        "ID": 36,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARIOCH",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE ELASAR"
    },
    {
        "ID": 37,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ARODI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GAD E NET DE JACÓ"
    },
    {
        "ID": 38,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ASBEL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 39,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ASENATH",
        "Book": "GENESE",
        "Chapter": 41,
        "Verse": 50,
        "Lifespan": "DESCONHECIDO",
        "Complement": "ESPOSA DE JOSÉ E FILHA DE POTÍFERA"
    },
    {
        "ID": 40,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ASER",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JACOB COM ZILPA SERVA DE LEA"
    },
    {
        "ID": 41,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ASQUENAZ",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GOMER, NETO DE JEFETH E BISNETO DE NOÉ"
    },
    {
        "ID": 42,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ASSUR",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SEM E NETO DE NOÉ"
    },
    {
        "ID": 43,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "ASSURIM",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DEDAN, NETO DE JOCSAN E BISNETO DE ABRAÃO"
    },
    {
        "ID": 44,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AUZATH",
        "Book": "GENESE",
        "Chapter": 26,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "AMIGO DE ABIMELECH"
    },
    {
        "ID": 45,
        "Index": NaN,
        "Alphabetical_Order": "A",
        "Name": "AZARMAVETH",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 46,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BAAL-ANAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 38,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ACBOR E REI DE EDOM"
    },
    {
        "ID": 47,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BASMATH",
        "Book": "GENESE",
        "Chapter": 26,
        "Verse": 34,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER D ESAÚ E FILHA DE ELON HETEU."
    },
    {
        "ID": 48,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BECHER",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 49,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BECHER",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 50,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BELA",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE ZOAR"
    },
    {
        "ID": 51,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BELA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 52,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BELA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 32,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BEOR REI DE EDON"
    },
    {
        "ID": 53,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BENAMI",
        "Book": "GENESE",
        "Chapter": 19,
        "Verse": 38,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LOTH COM SUA FILHA MAIS NOVA, DELE SURGIU OS FILHOS DE AMON"
    },
    {
        "ID": 54,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BENJAMIM/BENONI",
        "Book": "GENESE",
        "Chapter": 35,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO MAIS NOVO DE JACOB COM RAQUEL"
    },
    {
        "ID": 55,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BEOR",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 32,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PAI DO REI BELA"
    },
    {
        "ID": 56,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BERA",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE SODOMA"
    },
    {
        "ID": 57,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BERIA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ASER E NETO DE JACÓ"
    },
    {
        "ID": 58,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BETUEL",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 59,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BILHA",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "SERVA DE RAQUEL"
    },
    {
        "ID": 60,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BILHAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 27,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESER NETO DE SEIR"
    },
    {
        "ID": 61,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BIRSHA",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE GOMORRA"
    },
    {
        "ID": 62,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BOZRA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 33,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PAI DO REI JOBABE"
    },
    {
        "ID": 63,
        "Index": NaN,
        "Alphabetical_Order": "B",
        "Name": "BUZ",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 64,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CAFTORIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 65,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CAÍM",
        "Book": "GENESE",
        "Chapter": 3,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE ADÃO E LAVRADOR DE TERRA"
    },
    {
        "ID": 66,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CAINAM",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 9,
        "Lifespan": 910,
        "Complement": "PRIMOGENITO DE ENOS E BISNETO DE ADÃO"
    },
    {
        "ID": 67,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CAM",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 32,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NOÉ"
    },
    {
        "ID": 68,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CANAÃ",
        "Book": "GENESE",
        "Chapter": 9,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE CAM E NETO DE NOÉ"
    },
    {
        "ID": 69,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CARMI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 9,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE RUBEN E NETO DE JACÓ"
    },
    {
        "ID": 70,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CASIUSHIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 71,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CHEDORLAOMER",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE ELAM"
    },
    {
        "ID": 72,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CHERAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DISON, NETO DE ANA E BISNETO DE SEIR"
    },
    {
        "ID": 73,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CHESED",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 74,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "COATH",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LEVI E NETO DE JACÓ"
    },
    {
        "ID": 75,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CORA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 5,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESAÚ COM AOLIBAMA"
    },
    {
        "ID": 76,
        "Index": NaN,
        "Alphabetical_Order": "C",
        "Name": "CUSH",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 6,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CAM E NETO DE NOÉ"
    },
    {
        "ID": 77,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DAN",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 6,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCOB COM BILHA SERVA DE RAQUEL"
    },
    {
        "ID": 78,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DÉBORA",
        "Book": "GENESE",
        "Chapter": 35,
        "Verse": 8,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MÃE DE REBECA"
    },
    {
        "ID": 79,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DEDAN",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE RAAMA, NETO DE CUSH, BISNETO DE CAM E TATARANETO DE NOÉ"
    },
    {
        "ID": 80,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DEDAN",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCSAN E NETO DE ABRAÃO"
    },
    {
        "ID": 81,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DEUS",
        "Book": "GENESE",
        "Chapter": 1,
        "Verse": 1,
        "Lifespan": "TODOS",
        "Complement": "O CRIADOR"
    },
    {
        "ID": 82,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DICLA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 27,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 83,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DINA",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE JACOB COM LEA"
    },
    {
        "ID": 84,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DISAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 85,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DISON",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 86,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DISON",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 25,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ANA E NETO DE SEIR"
    },
    {
        "ID": 87,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DODANIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JAVAN, NETO DE JEFETHE E BISNETO DE NOÉ"
    },
    {
        "ID": 88,
        "Index": NaN,
        "Alphabetical_Order": "D",
        "Name": "DUMA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 89,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EBAL",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SOBAL E NETO DE SEIR"
    },
    {
        "ID": 90,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EBER",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ARFACHAD, NETO DE SEM E BISNETO DE NOÉ"
    },
    {
        "ID": 91,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ECHI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 92,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EFA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIDIAN E NETO DE ABRAÃO"
    },
    {
        "ID": 93,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EFER",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIDIAN E NETO DE ABRAÃO"
    },
    {
        "ID": 94,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EFRAIM",
        "Book": "GENESE",
        "Chapter": 41,
        "Verse": 52,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOSÉ"
    },
    {
        "ID": 95,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EFRON",
        "Book": "GENESE",
        "Chapter": 23,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE HETH"
    },
    {
        "ID": 96,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELÁ",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 41,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 97,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELAM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SEM E NETO DE NOÉ"
    },
    {
        "ID": 98,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELDA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIDIAN E NETO DE ABRAÃO"
    },
    {
        "ID": 99,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELIESER",
        "Book": "GENESE",
        "Chapter": 15,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MORDOMO DE ABRÃO"
    },
    {
        "ID": 100,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELIFAZ",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESAÚ COM ADA"
    },
    {
        "ID": 101,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELISA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JAVAN, NETO DE JEFETHE E BISNETO DE NOÉ"
    },
    {
        "ID": 102,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ELON",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ZEBULON E NETO DE JACÓ"
    },
    {
        "ID": 103,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ENOS",
        "Book": "GENESE",
        "Chapter": 3,
        "Verse": 26,
        "Lifespan": 905,
        "Complement": "PRIMOGENITO DE SETH E NETO DE ADÃO"
    },
    {
        "ID": 104,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ER",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE JUDÁ COM SUA"
    },
    {
        "ID": 105,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ESAÚ",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 25,
        "Lifespan": "DESCONHECIDO",
        "Complement": "O PRIOGENITO DE ISAAC E IRMÃO GEMIO DE JACOB"
    },
    {
        "ID": 106,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ESBAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DISON, NETO DE ANA E BISNETO DE SEIR"
    },
    {
        "ID": 107,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ESCOL",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "CONFEDERADO DE ABRÃO"
    },
    {
        "ID": 108,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ESER",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 109,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "ÉVA",
        "Book": "GENESE",
        "Chapter": 3,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMEIRA MULHER"
    },
    {
        "ID": 110,
        "Index": NaN,
        "Alphabetical_Order": "E",
        "Name": "EZBON",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GAD E NET DE JACÓ"
    },
    {
        "ID": 111,
        "Index": NaN,
        "Alphabetical_Order": "F",
        "Name": "FICOL",
        "Book": "GENESE",
        "Chapter": 21,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DO EXÉRCITO DE DO REI ABIMELECH"
    },
    {
        "ID": 112,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GAAM",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR COM SUA CONCUBINA REUMA"
    },
    {
        "ID": 113,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GAD",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JACOB COM ZILPA SERVA DE LEA"
    },
    {
        "ID": 114,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GAETAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ELIFAZ"
    },
    {
        "ID": 115,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GERA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 116,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GERSON",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LEVI E NETO DE JACÓ"
    },
    {
        "ID": 117,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GETER",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ARAM, NETO DE SEM E BISNETO DE NOÉ"
    },
    {
        "ID": 118,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GOMER",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 119,
        "Index": NaN,
        "Alphabetical_Order": "G",
        "Name": "GUNI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NAFTALI E NETO DE JACÓ"
    },
    {
        "ID": 120,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HADA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 121,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HAMUL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 12,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE PEREZ, NETO DE JUDÁ E BISNETO DE JACÓ"
    },
    {
        "ID": 122,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HANOCH",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 9,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE RUBEN E NETO DE JACÓ"
    },
    {
        "ID": 123,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HARAN",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE TERA"
    },
    {
        "ID": 124,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HAVILÁ",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 125,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HAVILA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CUSH, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 126,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HAZO",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 127,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HEBER",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BERIA, NETO DE ASER E BISNETO DE JACÓ"
    },
    {
        "ID": 128,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HEMAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LOTAN E NETO DE SEIR"
    },
    {
        "ID": 129,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HEMDAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DISON, NETO DE ANA E BISNETO DE SEIR"
    },
    {
        "ID": 130,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HEMOR",
        "Book": "GENESE",
        "Chapter": 33,
        "Verse": 19,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PAI DE SIQUÉM O PRINCIPE"
    },
    {
        "ID": 131,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HENOCH",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE CAIM"
    },
    {
        "ID": 132,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HENOCH",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 18,
        "Lifespan": "FICOU NA TERRA 365 ANOS E DEUS TOMOU PARA SI, E TEORICAMENTE AINDA ESTÁ VIVO.",
        "Complement": "PRIMOGENITO DE JARED"
    },
    {
        "ID": 133,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HENOCH",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIDIAN E NETO DE ABRAÃO"
    },
    {
        "ID": 134,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HETH",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CANAÃ, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 135,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HEZRON",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 9,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE RUBEN E NETO DE JACÓ"
    },
    {
        "ID": 136,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HEZRON",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 12,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE PEREZ, NETO DE JUDÁ E BISNETO DE JACÓ"
    },
    {
        "ID": 137,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HIRA",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "HOMEM DE ADULAM"
    },
    {
        "ID": 138,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HORI",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LOTAN E NETO DE SEIR"
    },
    {
        "ID": 139,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HUPIM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 140,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HUSÃO",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 34,
        "Lifespan": "DESCONHECIDO",
        "Complement": "DA TERRA DOS TEMATITAS E REI DE EDOM"
    },
    {
        "ID": 141,
        "Index": NaN,
        "Alphabetical_Order": "H",
        "Name": "HUSIM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DAN E NETO DE JACÓ"
    },
    {
        "ID": 142,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "IMNA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ASER E NETO DE JACÓ"
    },
    {
        "ID": 143,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "IRAD",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE HENOCH E NETO DE CAIM"
    },
    {
        "ID": 144,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "IRAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 43,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 145,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ISAAC",
        "Book": "GENESE",
        "Chapter": 21,
        "Verse": 3,
        "Lifespan": 180,
        "Complement": "FILHO DE ABRÃO COM SARAI"
    },
    {
        "ID": 146,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ISCAH",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE HARAN"
    },
    {
        "ID": 147,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ISCHVA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ASER E NETO DE JACÓ"
    },
    {
        "ID": 148,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ISCHVI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ASER E NETO DE JACÓ"
    },
    {
        "ID": 149,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ISMAEL",
        "Book": "GENESE",
        "Chapter": 16,
        "Verse": 11,
        "Lifespan": 137,
        "Complement": "FILHO DE ABRÃO COM AGAR A EGÍPCIA"
    },
    {
        "ID": 150,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ISSACAR",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FIHO DE JACOB COM LEA"
    },
    {
        "ID": 151,
        "Index": NaN,
        "Alphabetical_Order": "I",
        "Name": "ITRAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DISON, NETO DE ANA E BISNETO DE SEIR"
    },
    {
        "ID": 152,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JAALAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 5,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESAÚ COM AOLIBAMA"
    },
    {
        "ID": 153,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JABAL",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LAMECH COM ADA; ESTE FOI O PAI DOS QUE ABITAM EM TENDAS E TEM GADO"
    },
    {
        "ID": 154,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JACOB",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 26,
        "Lifespan": 147,
        "Complement": "FILHO DE ISAAC E IRMÃO GEMIO DE ESAÚ"
    },
    {
        "ID": 155,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JAFETH",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 32,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NOÉ"
    },
    {
        "ID": 156,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JÁLEEL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ZEBULON E NETO DE JACÓ"
    },
    {
        "ID": 157,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JAMIM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SIMEÃO E NETO DE JACÓ"
    },
    {
        "ID": 158,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JAQUIM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SIMEÃO E NETO DE JACÓ"
    },
    {
        "ID": 159,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JARED",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 16,
        "Lifespan": 962,
        "Complement": "PRIMOGENITO DE MAALALEL"
    },
    {
        "ID": 160,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JAVAN",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 161,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JÁZEEL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NAFTALI E NETO DE JACÓ"
    },
    {
        "ID": 162,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JEMUEL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SIMEÃO E NETO DE JACÓ"
    },
    {
        "ID": 163,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JEOVÁ",
        "Book": "GENESE",
        "Chapter": 15,
        "Verse": 2,
        "Lifespan": "TODOS",
        "Complement": "O CRIADOR"
    },
    {
        "ID": 164,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JERA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 165,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JETETH",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 40,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 166,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JETUR",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 167,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JEUS",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 5,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESAÚ COM AOLIBAMA"
    },
    {
        "ID": 168,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JEZER",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NAFTALI E NETO DE JACÓ"
    },
    {
        "ID": 169,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JIDLAF",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 170,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JÓ",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISSACAR E NETO DE JACÓ"
    },
    {
        "ID": 171,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JOBABE",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 172,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JOBABE",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 33,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ZERÁ COM BOZRA REI DE EDOM"
    },
    {
        "ID": 173,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JOCSAN",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ABRAÃO COM KETURA"
    },
    {
        "ID": 174,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JOCTAN",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 25,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE EBER, NETO D ARFACHAD, BISNETO DE SEM E TATARANETO DE NOÉ"
    },
    {
        "ID": 175,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JOSÉ",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 25,
        "Lifespan": 110,
        "Complement": "FILHO DE JACOB COM RAQUEL"
    },
    {
        "ID": 176,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JUBAL",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LAMECH COM ADA; ESTE FOI O PAI DOS QUE TOCAM HARPA E ÓRGÃO"
    },
    {
        "ID": 177,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JUDÁ",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 35,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JACOB COM LEA"
    },
    {
        "ID": 178,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JUDITE",
        "Book": "GENESE",
        "Chapter": 26,
        "Verse": 34,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER DE ESAÚ FILHA DE BEERI, HETEU."
    },
    {
        "ID": 179,
        "Index": NaN,
        "Alphabetical_Order": "J",
        "Name": "JUISBAC",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ABRAÃO COM KETURA"
    },
    {
        "ID": 180,
        "Index": NaN,
        "Alphabetical_Order": "K",
        "Name": "KEMUEL",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 181,
        "Index": NaN,
        "Alphabetical_Order": "K",
        "Name": "KETURA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "SEGUNDA MULHER DE ABRAÃO"
    },
    {
        "ID": 182,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LABÃO",
        "Book": "GENESE",
        "Chapter": 24,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BETUEL E IRMÃO DE REBECA"
    },
    {
        "ID": 183,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LAMECH",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FPRIMOGENITO DE METUSAEL"
    },
    {
        "ID": 184,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LAMECH",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 25,
        "Lifespan": 767,
        "Complement": "PRIMGENITO DE METUSALA"
    },
    {
        "ID": 185,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LEABIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 186,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LEABIM",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA MAIS VELHA DE LABÃO"
    },
    {
        "ID": 187,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LETUSIM",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DEDAN, NETO DE JOCSAN E BISNETO DE ABRAÃO"
    },
    {
        "ID": 188,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LEUMIM",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DEDAN, NETO DE JOCSAN E BISNETO DE ABRAÃO"
    },
    {
        "ID": 189,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LEVI",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 34,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCOB COM LEA"
    },
    {
        "ID": 190,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LOTAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 191,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LOTH",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 31,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE HARAN E NETO DE TERA"
    },
    {
        "ID": 192,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LUDIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 193,
        "Index": NaN,
        "Alphabetical_Order": "L",
        "Name": "LUDIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SEM E NETO DE NOÉ"
    },
    {
        "ID": 194,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAACA",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR COM SUA CONCUBINA REUMA"
    },
    {
        "ID": 195,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAALALEL",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 12,
        "Lifespan": 895,
        "Complement": "PRIMOGENITO DE CAINAM E TATARANETO DE ADÃO"
    },
    {
        "ID": 196,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAALATH",
        "Book": "GENESE",
        "Chapter": 28,
        "Verse": 9,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER DE ESAÚ FILHA DE ISMAEL, FILH DE ABRAÃO"
    },
    {
        "ID": 197,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MADAI",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 198,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAGDIEL",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 43,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 199,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAGOG",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 200,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MALQUIEL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BERIA, NETO DE ASER E BISNETO DE JACÓ"
    },
    {
        "ID": 201,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAMRE",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "LUTOU AO LADO DE ABRÃO NO VALE DE SIDIM"
    },
    {
        "ID": 202,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MANAATH",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SOBAL E NETO DE SEIR"
    },
    {
        "ID": 203,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MANASSÉS",
        "Book": "GENESE",
        "Chapter": 41,
        "Verse": 51,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGÉNITO DE JOSÉ"
    },
    {
        "ID": 204,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MAS",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ARAM, NETO DE SEM E BISNETO DE NOÉ"
    },
    {
        "ID": 205,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MASSA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 206,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MATRED",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 39,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MÃE DE MEETABEL"
    },
    {
        "ID": 207,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MEDAN",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ABRAÃO COM KETURA"
    },
    {
        "ID": 208,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MEETABEL",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 39,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE MATRED E MEZAAB, E MULHER DO REI ADAR"
    },
    {
        "ID": 209,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MELQUISEDEC",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "SACERDOTE DO DEUS ALTÍSSIMO"
    },
    {
        "ID": 210,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MERARI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LEVI E NETO DE JACÓ"
    },
    {
        "ID": 211,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MESECH",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 212,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "METUSAEL",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE MEUJAEL E TATARANETO DE CAIM"
    },
    {
        "ID": 213,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "METUSALA",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 21,
        "Lifespan": 969,
        "Complement": "PRIMOGENITO DE HENOCH"
    },
    {
        "ID": 214,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MEUJAEL",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMGENITO DE IRAD E BISNETO DE CAIM"
    },
    {
        "ID": 215,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MEZAAB",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 39,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PAI DE MEETABEL"
    },
    {
        "ID": 216,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MIBSAM",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 217,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MIBZAR",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 42,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 218,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MIDIAN",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ABRAÃO COM KETURA"
    },
    {
        "ID": 219,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MILCA",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE HARAN E MULHER DE NACOR"
    },
    {
        "ID": 220,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MISMA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 221,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MIZA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE REUEL"
    },
    {
        "ID": 222,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MIZRAIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 6,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CAM E NETO DE NOÉ"
    },
    {
        "ID": 223,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MOAB",
        "Book": "GENESE",
        "Chapter": 19,
        "Verse": 37,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LOTH COM SUA FILHA MAIS VELHA, E DELE SURGIU OD MOABITAS"
    },
    {
        "ID": 224,
        "Index": NaN,
        "Alphabetical_Order": "M",
        "Name": "MUPIM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 225,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NAAMA",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE LAMECH CM ZILA IRMÃ DE TUBALCAIM"
    },
    {
        "ID": 226,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NAAMAN",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 227,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NAATH",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE REUEL"
    },
    {
        "ID": 228,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NACOR",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SERUG, NETO DE REÚ, BISNETO DE PELEG, TATARANETO DE EBER"
    },
    {
        "ID": 229,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NACOR",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE TERA"
    },
    {
        "ID": 230,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NAFIS",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 231,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NAFTALI",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 8,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JACOB COM BILHA SERVA DE RAQUEL"
    },
    {
        "ID": 232,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NEBAJOTH",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE ISMAEL"
    },
    {
        "ID": 233,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NEFTUIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 234,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NIMROD",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 8,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CUSH, NETO DE CAM E BISNETO DE NOÉ. (PODEROSO CASADOR DIANTE DO SENHOR)"
    },
    {
        "ID": 235,
        "Index": NaN,
        "Alphabetical_Order": "N",
        "Name": "NOÉ",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 29,
        "Lifespan": 950,
        "Complement": "PRIMOGENITO DE LAMECH E NETO DE METUSALA, CONSTRUTOR DA ARCA"
    },
    {
        "ID": 236,
        "Index": NaN,
        "Alphabetical_Order": "O",
        "Name": "OAD",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SIMEÃO E NETO DE JACÓ"
    },
    {
        "ID": 237,
        "Index": NaN,
        "Alphabetical_Order": "O",
        "Name": "OBAL",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 28,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 238,
        "Index": NaN,
        "Alphabetical_Order": "O",
        "Name": "OFIR",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 239,
        "Index": NaN,
        "Alphabetical_Order": "O",
        "Name": "OMAR",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ELIFAZ"
    },
    {
        "ID": 240,
        "Index": NaN,
        "Alphabetical_Order": "O",
        "Name": "ONAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SOBAL E NETO DE SEIR"
    },
    {
        "ID": 241,
        "Index": NaN,
        "Alphabetical_Order": "O",
        "Name": "ONAN",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JUDÁ COM SUA"
    },
    {
        "ID": 242,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PALU",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 9,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE RUBEN E NETO DE JACÓ"
    },
    {
        "ID": 243,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PATRUSIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE MIZRAIM, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 244,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PELEG",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 25,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE EBER, NETO D ARFACHAD, BISNETO DE SEM E TATARANETO DE NOÉ. (PORTANTO EM SEUS DIAS REPARTIAM A TERRA)"
    },
    {
        "ID": 245,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PEREZ",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 29,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JUDÁ COM TAMAR SUA NORA"
    },
    {
        "ID": 246,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PILDAS",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 247,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PINON",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 41,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 248,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "POTIFAR",
        "Book": "GENESE",
        "Chapter": 37,
        "Verse": 36,
        "Lifespan": "DESCONHECIDO",
        "Complement": "EUNUCO DE FARAÓ"
    },
    {
        "ID": 249,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "POTÍFERA",
        "Book": "GENESE",
        "Chapter": 41,
        "Verse": 50,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PAI DE ASENATH E SARCERDOTE DE ON"
    },
    {
        "ID": 250,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PUA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISSACAR E NETO DE JACÓ"
    },
    {
        "ID": 251,
        "Index": NaN,
        "Alphabetical_Order": "P",
        "Name": "PUT",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 6,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CAM E NETO DE NOÉ"
    },
    {
        "ID": 252,
        "Index": NaN,
        "Alphabetical_Order": "Q",
        "Name": "QUEDAR",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 253,
        "Index": NaN,
        "Alphabetical_Order": "Q",
        "Name": "QUEDMA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 254,
        "Index": NaN,
        "Alphabetical_Order": "Q",
        "Name": "QUENAZ",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ELIFAZ"
    },
    {
        "ID": 255,
        "Index": NaN,
        "Alphabetical_Order": "Q",
        "Name": "QUENAZ",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 42,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 256,
        "Index": NaN,
        "Alphabetical_Order": "Q",
        "Name": "QUETIM",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JAVAN, NETO DE JEFETHE E BISNETO DE NOÉ"
    },
    {
        "ID": 257,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "RAAMA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CUSH, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 258,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "RAQUEL",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 6,
        "Lifespan": "DESCONHECIDO",
        "Complement": "RAQUEL FILHA DE LABÃO"
    },
    {
        "ID": 259,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "REBECA",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE BETUEL"
    },
    {
        "ID": 260,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "REÚ",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 18,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE PELEG, NETO DE EBER, BISNETO DE SEM E TATARANETO DE NOÉ"
    },
    {
        "ID": 261,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "REUEL",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESAÚ COM BASEMATH"
    },
    {
        "ID": 262,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "REUMA",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR COM SUA CONCUBINA REUMA"
    },
    {
        "ID": 263,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "RIFATH",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GOMER, NETO DE JEFETH E BISNETO DE NOÉ"
    },
    {
        "ID": 264,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "ROS",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE BENJAMIM E NETO DE JACÓ"
    },
    {
        "ID": 265,
        "Index": NaN,
        "Alphabetical_Order": "R",
        "Name": "RUBEN",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 32,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE JACOB COM LEA"
    },
    {
        "ID": 266,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SABTECA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CUSH, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 267,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SAMLA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 36,
        "Lifespan": "DESCONHECIDO",
        "Complement": "DA TERRA DE MASRECA REI DE EDOM"
    },
    {
        "ID": 268,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SARAI/SARA",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 29,
        "Lifespan": 127,
        "Complement": "FILHA DE TERA E MUHER DE ABRÃO"
    },
    {
        "ID": 269,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SARED",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 14,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ZEBULON E NETO DE JACÓ"
    },
    {
        "ID": 270,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SAUL",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 37,
        "Lifespan": "DESCONHECIDO",
        "Complement": "DA TERRA DE REOBOTH DO RI REI DE EDOM"
    },
    {
        "ID": 271,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SAUL",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SIMEÃO COM UMA MULHER CANANEIA, E NETO DE JACÓ"
    },
    {
        "ID": 272,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SCEBA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE RAAMA, NETO DE CUSH, BISNETO DE CAM E TATARANETO DE NOÉ"
    },
    {
        "ID": 273,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SEBA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CUSH, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 274,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SEBA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 28,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 275,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SEBA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCSAN E NETO DE ABRAÃO"
    },
    {
        "ID": 276,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SEBTA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 7,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE CUSH, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 277,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SEIR",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MORADOR DE EDOM"
    },
    {
        "ID": 278,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SELA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ARFACHAD, NETO DE SEM E BISNETO DE NOÉ"
    },
    {
        "ID": 279,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SELA",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 5,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JUDÁ COM SUA"
    },
    {
        "ID": 280,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SEM",
        "Book": "GENESE",
        "Chapter": 5,
        "Verse": 32,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE NOÉ"
    },
    {
        "ID": 281,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SERA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 17,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHA DE ASER E NETA DE JACÓ"
    },
    {
        "ID": 282,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SERUG",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE REÚ, NETO DE PELEG, BISNETO DE EBER E TATARANETO DE SEM"
    },
    {
        "ID": 283,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SETH",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 25,
        "Lifespan": 912,
        "Complement": "FILHO DE ADÃO E EVA"
    },
    {
        "ID": 284,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SHAMA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE REUEL"
    },
    {
        "ID": 285,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SHEFO",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SOBAL E NETO DE SEIR"
    },
    {
        "ID": 286,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SHELEF",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 26,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 287,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SHEMEBER",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE ZEBOIIM"
    },
    {
        "ID": 288,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SHINAB",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "REI DE ADMAH"
    },
    {
        "ID": 289,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SHUNI",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GAD E NETO DE JACÓ"
    },
    {
        "ID": 290,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SIDON",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE CANAÃ, NETO DE CAM E BISNETO DE NOÉ"
    },
    {
        "ID": 291,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SILÉM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NAFTALI E NETO DE JACÓ"
    },
    {
        "ID": 292,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SIMEÃO",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 33,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JACOB COM LEA"
    },
    {
        "ID": 293,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SINROM",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISSACAR E NETO DE JACÓ"
    },
    {
        "ID": 294,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SIQUÉM",
        "Book": "GENESE",
        "Chapter": 33,
        "Verse": 19,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE HEMOR HEVEU"
    },
    {
        "ID": 295,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SOBAL",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 296,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SUA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ABRAÃO COM KETURA"
    },
    {
        "ID": 297,
        "Index": NaN,
        "Alphabetical_Order": "S",
        "Name": "SUA",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER DE JUDÁ"
    },
    {
        "ID": 298,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TAASH",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR COM SUA CONCUBINA REUMA"
    },
    {
        "ID": 299,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TAMAR",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 6,
        "Lifespan": "DESCONHECIDO",
        "Complement": "NÓRA DE JUDÁ"
    },
    {
        "ID": 300,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TARSIS",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 4,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JAVAN, NETO DE JEFETHE E BISNETO DE NOÉ"
    },
    {
        "ID": 301,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TEDAH",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE NACOR COM SUA CONCUBINA REUMA"
    },
    {
        "ID": 302,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TEMA",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 15,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISMAEL"
    },
    {
        "ID": 303,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TEMAM",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ELIFAZ"
    },
    {
        "ID": 304,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TEMAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 42,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRÍNCIPE DE EDOM"
    },
    {
        "ID": 305,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TERA",
        "Book": "GENESE",
        "Chapter": 11,
        "Verse": 24,
        "Lifespan": 205,
        "Complement": "FILHO DE NACOR, NETO DE SERUB, BISNETO DE REÚ E TATARANETO DE PELEG"
    },
    {
        "ID": 306,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TIBAL",
        "Book": "GENESE",
        "Chapter": 14,
        "Verse": 1,
        "Lifespan": "DESCONHECIDO",
        "Complement": "GOIIM"
    },
    {
        "ID": 307,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TIMNA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 12,
        "Lifespan": "DESCONHECIDO",
        "Complement": "CONCUBINA DE ELIFAZ"
    },
    {
        "ID": 308,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TIRAS",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 309,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TOGARMA",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 3,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GOMER, NETO DE JEFETH E BISNETO DE NOÉ"
    },
    {
        "ID": 310,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TOLA",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ISSACAR E NETO DE JACÓ"
    },
    {
        "ID": 311,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TUBAL",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JEFETH E NETO DE NOÉ"
    },
    {
        "ID": 312,
        "Index": NaN,
        "Alphabetical_Order": "T",
        "Name": "TUBALCAIM",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 22,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE LAMECH COM ZILA; ESTE MESTRE DE TODA OBRA DE COBRE E DE FERRO"
    },
    {
        "ID": 313,
        "Index": NaN,
        "Alphabetical_Order": "U",
        "Name": "UL",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ARAM, NETO DE SEM E BISNETO DE NOÉ"
    },
    {
        "ID": 314,
        "Index": NaN,
        "Alphabetical_Order": "U",
        "Name": "UZ",
        "Book": "GENESE",
        "Chapter": 22,
        "Verse": 21,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRIMOGENITO DE NACOR E SOBRINHO DE ABRÃO"
    },
    {
        "ID": 315,
        "Index": NaN,
        "Alphabetical_Order": "U",
        "Name": "UZ",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 28,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE DISAN E NETO DE SEIR"
    },
    {
        "ID": 316,
        "Index": NaN,
        "Alphabetical_Order": "U",
        "Name": "UZ",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 23,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ARAM, NETO DE SEM E BISNETO DE NOÉ"
    },
    {
        "ID": 317,
        "Index": NaN,
        "Alphabetical_Order": "U",
        "Name": "UZAL",
        "Book": "GENESE",
        "Chapter": 10,
        "Verse": 27,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JOCTAN, NETO DE EBER, BISNETO DE ARFACHAD E TATARANETO DE SEM"
    },
    {
        "ID": 318,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZAAVAN",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 27,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ESER NETO DE SEIR"
    },
    {
        "ID": 319,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZEBULON",
        "Book": "GENESE",
        "Chapter": 30,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FIHO DE JACOB COM LEA"
    },
    {
        "ID": 320,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZEFO",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 11,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ELIFAZ"
    },
    {
        "ID": 321,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZERA",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 13,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE REUEL"
    },
    {
        "ID": 322,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZERA",
        "Book": "GENESE",
        "Chapter": 38,
        "Verse": 30,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE JUDÁ COM TAMAR SUA NORA"
    },
    {
        "ID": 323,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZERÁ",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 33,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MÃE DO REI JOBABE"
    },
    {
        "ID": 324,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZIBEON",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SEIR, PAI DE AOLIBAMA MULHER DE ESAÚ"
    },
    {
        "ID": 325,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZIBEON",
        "Book": "GENESE",
        "Chapter": 36,
        "Verse": 20,
        "Lifespan": "DESCONHECIDO",
        "Complement": "PRINCIPE, FILHO DE SEIR MORADOR DE EDOM"
    },
    {
        "ID": 326,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZIFION",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 16,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE GAD E NET DE JACÓ"
    },
    {
        "ID": 327,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZILA",
        "Book": "GENESE",
        "Chapter": 4,
        "Verse": 19,
        "Lifespan": "DESCONHECIDO",
        "Complement": "MULHER DE LAMECH"
    },
    {
        "ID": 328,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZILPA",
        "Book": "GENESE",
        "Chapter": 29,
        "Verse": 24,
        "Lifespan": "DESCONHECIDO",
        "Complement": "SERVA DE LEA"
    },
    {
        "ID": 329,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZIMRAN",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 2,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE ABRAÃO COM KETURA"
    },
    {
        "ID": 330,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZOAR",
        "Book": "GENESE",
        "Chapter": 25,
        "Verse": 9,
        "Lifespan": "DESCONHECIDO",
        "Complement": "O HETEU PAI DE EFRON"
    },
    {
        "ID": 331,
        "Index": NaN,
        "Alphabetical_Order": "Z",
        "Name": "ZOAR",
        "Book": "GENESE",
        "Chapter": 46,
        "Verse": 10,
        "Lifespan": "DESCONHECIDO",
        "Complement": "FILHO DE SIMEÃO COM UMA MULHER CANANEIA, E NETO DE JACÓ"
    }
]